use index_tests;

show indexes from large_table_1;

SELECT DISTINCT
    TABLE_NAME,
INDEX_NAME
FROM INFORMATION_SCHEMA.STATISTICS 
WHERE TABLE_SCHEMA = 'index_tests';

SELECT DISTINCT
    TABLE_NAME,
INDEX_NAME
FROM INFORMATION_SCHEMA.STATISTICS 
WHERE TABLE_SCHEMA = 'sakila';


SELECT DISTINCT
    TABLE_NAME,
INDEX_NAME
FROM INFORMATION_SCHEMA.STATISTICS 
WHERE TABLE_SCHEMA = 'world';

